name: shopping_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  delayed_widget: ^1.1.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  connectivity_plus: ^6.0.1
  loading_animation_widget: ^1.2.0+3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  get_it: ^7.2.0
  dio: ^5.4.1
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.2.1
  badges: ^3.1.2
  cached_network_image: ^3.2.2
  location: ^5.0.3
  flutter_typeahead: ^5.2.0
  flutter_rating_bar: ^4.0.1
#  android_sms_retriever: ^1.3.2
  persian_number_utility: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/vazir.ttf